-- MySQL Script generated by MySQL Workbench
-- Sun Mar 15 01:47:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UserID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RobotRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RobotRoles` (
  `RobotRoleID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotRole` VARCHAR(45) NULL DEFAULT 'ENUM'[Role1, Role2],
  `UserID` INT UNSIGNED NOT NULL,
  `AIResponseID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotRoleID`),
  CONSTRAINT `FK_RobotRole_UserID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manufacturers` (
  `ManufacturerID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ManufacturerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RobotModels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RobotModels` (
  `RobotModelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Model` VARCHAR(45) NULL DEFAULT 'ENUM'[Model1, Model2],
  `ManufacturerID` INT UNSIGNED NULL,
  PRIMARY KEY (`RobotModelID`),
  INDEX `FK_RobotModel_ManufacturerID_idx` (`ManufacturerID` ASC) VISIBLE,
  CONSTRAINT `FK_RobotModel_ManufacturerID`
    FOREIGN KEY (`ManufacturerID`)
    REFERENCES `mydb`.`Manufacturers` (`ManufacturerID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `AddressID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(90) NOT NULL,
  `City` VARCHAR(90) NOT NULL,
  `State` VARCHAR(50) NULL,
  `Zipcode` VARCHAR(20) NULL,
  PRIMARY KEY (`AddressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeploymentLocations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeploymentLocations` (
  `DeploymentLocationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EnvironmentType` ENUM('HOME', 'HOSPITAL', 'WAREHOUSE', 'FACTORY') NOT NULL,
  `AddressID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DeploymentLocationID`),
  INDEX `FK_DeploymentLocation_AdressID_idx` (`AddressID` ASC) VISIBLE,
  CONSTRAINT `FK_DeploymentLocation_AdressID`
    FOREIGN KEY (`AddressID`)
    REFERENCES `mydb`.`Addresses` (`AddressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SoftwareVersion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SoftwareVersion` (
  `SoftwareVersionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SoftwareVersionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Robots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Robots` (
  `RobotID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotRoleID` INT UNSIGNED NOT NULL,
  `RobotModelID` INT UNSIGNED NOT NULL,
  `DeploymentLocationID` INT UNSIGNED NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `SoftwareVersionID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotID`),
  INDEX `FK_Robot_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  INDEX `FK_Robot_RobotRoleID_idx` (`RobotRoleID` ASC) VISIBLE,
  INDEX `FK_Robot_RobotModelID_idx` (`RobotModelID` ASC) VISIBLE,
  INDEX `FK_Robot_SoftwareVersionID_idx` (`SoftwareVersionID` ASC) VISIBLE,
  INDEX `FK_Robot_UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_Robot_RobotRoleID`
    FOREIGN KEY (`RobotRoleID`)
    REFERENCES `mydb`.`RobotRoles` (`RobotRoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_RobotModelID`
    FOREIGN KEY (`RobotModelID`)
    REFERENCES `mydb`.`RobotModels` (`RobotModelID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Robot_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_SoftwareVersionID`
    FOREIGN KEY (`SoftwareVersionID`)
    REFERENCES `mydb`.`SoftwareVersion` (`SoftwareVersionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alerts` (
  `AlertID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `Severity` VARCHAR(45) NOT NULL DEFAULT 'ENUM'[Model1, Model2],
  `TimeStamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`AlertID`),
  INDEX `FK_Alert_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_Alert_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PerformanceMetrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PerformanceMetrics` (
  `PerformanceMetricID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `MetricType` VARCHAR(45) NOT NULL,
  `MetricValue` INT UNSIGNED NOT NULL,
  `TimeStamp` DATETIME NOT NULL,
  PRIMARY KEY (`PerformanceMetricID`),
  INDEX `FK_PerformanceMetrics_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_PerformanceMetrics_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technicians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technicians` (
  `TechnicianID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NULL,
  PRIMARY KEY (`TechnicianID`),
  INDEX `FK_Technician_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Technician_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tasks` (
  `TaskID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AIResponseID` INT UNSIGNED NOT NULL,
  `TaskName` VARCHAR(64) NOT NULL,
  `Description` TEXT NOT NULL,
  `Priority` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `Status` TINYINT NOT NULL,
  PRIMARY KEY (`TaskID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TaskAssignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TaskAssignments` (
  `TaskAssignmentID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `TaskID` INT UNSIGNED NOT NULL,
  `AssignedAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`TaskAssignmentID`),
  INDEX `fk_TaskAssignments_Robots1_idx` (`RobotID` ASC) VISIBLE,
  INDEX `fk_TaskAssignments_Users1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_TaskAssignments_Tasks1_idx` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `fk_TaskAssignments_Robots1`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaskAssignments_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaskAssignments_Tasks1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `mydb`.`Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TaskExecutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TaskExecutions` (
  `TaskExecutionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TaskID` INT UNSIGNED NOT NULL,
  `StartTime` TIMESTAMP NOT NULL,
  `EndTime` TIMESTAMP NOT NULL,
  `Status` TINYINT NOT NULL,
  PRIMARY KEY (`TaskExecutionID`),
  INDEX `fk_TaskExecutions_Tasks1_idx` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `fk_TaskExecutions_Tasks1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `mydb`.`Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hardware` (
  `HardwareID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ManufacturerID` INT UNSIGNED NULL,
  PRIMARY KEY (`HardwareID`),
  INDEX `FK_Hardware_ManufacturerID_idx` (`ManufacturerID` ASC) VISIBLE,
  CONSTRAINT `FK_Hardware_ManufacturerID`
    FOREIGN KEY (`ManufacturerID`)
    REFERENCES `mydb`.`Manufacturers` (`ManufacturerID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RobotHardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RobotHardware` (
  `RobotHardwareID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotHardwareID`),
  INDEX `FK_RobotHardware_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_RobotHardware_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChargingSessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ChargingSessions` (
  `ChargingSessionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  `StartTime` TIMESTAMP NOT NULL,
  `EndTime` TIMESTAMP NULL,
  PRIMARY KEY (`ChargingSessionID`),
  INDEX `FK_ChargingSession_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_ChargingSession_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EnergyStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EnergyStatus` (
  `EnergyStatusID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ChargingSessionID` INT UNSIGNED NOT NULL,
  `BatteryLevel` TINYINT(3) UNSIGNED NOT NULL,
  `RecordedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `RobotID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EnergyStatusID`),
  INDEX `FK_EnergyStatus_ChargingSessionID_idx` (`ChargingSessionID` ASC) VISIBLE,
  INDEX `FK_EnergyStatus_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_EnergyStatus_ChargingSessionID`
    FOREIGN KEY (`ChargingSessionID`)
    REFERENCES `mydb`.`ChargingSessions` (`ChargingSessionID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EnergyStatus_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChargingStations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ChargingStations` (
  `ChargingStationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `StationName` VARCHAR(64) NULL,
  `Capacity` TINYINT(3) UNSIGNED NOT NULL,
  `Status` ENUM('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'OFFLINE') NOT NULL DEFAULT 'AVAILABLE',
  PRIMARY KEY (`ChargingStationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChargingStationSessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ChargingStationSessions` (
  `ChargingSessionID` INT UNSIGNED NOT NULL,
  `ChargingStationID` INT UNSIGNED NOT NULL,
  INDEX `FK_ChargingStationSession_ChargingSessionID_idx` (`ChargingSessionID` ASC) VISIBLE,
  INDEX `FK_ChargingStationSession_ChargingStationID_idx` (`ChargingStationID` ASC) VISIBLE,
  PRIMARY KEY (`ChargingSessionID`, `ChargingStationID`),
  CONSTRAINT `FK_ChargingStationSession_ChargingSessionID`
    FOREIGN KEY (`ChargingSessionID`)
    REFERENCES `mydb`.`ChargingSessions` (`ChargingSessionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ChargingStationSession_ChargingStationID`
    FOREIGN KEY (`ChargingStationID`)
    REFERENCES `mydb`.`ChargingStations` (`ChargingStationID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RobotChargingStations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RobotChargingStations` (
  `ChargingStationID` INT UNSIGNED NOT NULL,
  `RobotID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ChargingStationID`, `RobotID`),
  INDEX `FK_RobotChargingStation_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_RobotChargingStation_ChargingStationID`
    FOREIGN KEY (`ChargingStationID`)
    REFERENCES `mydb`.`ChargingStations` (`ChargingStationID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RobotChargingStation_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logs` (
  `LogID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EventType` VARCHAR(64) NOT NULL,
  `EventDetails` TEXT(150) NULL,
  PRIMARY KEY (`LogID`),
  INDEX `FK_Log_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_Log_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TechnicianNames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TechnicianNames` (
  `TechnicianNameID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TechnicianID` INT UNSIGNED NOT NULL,
  `FirstName` VARCHAR(64) NOT NULL,
  `LastName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`TechnicianNameID`),
  INDEX `FK_TechnicanName_Technician_idx` (`TechnicianID` ASC) VISIBLE,
  CONSTRAINT `FK_TechnicanName_Technician`
    FOREIGN KEY (`TechnicianID`)
    REFERENCES `mydb`.`Technicians` (`TechnicianID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LogSessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LogSessions` (
  `ChargingSessionID` INT UNSIGNED NOT NULL,
  `LogID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ChargingSessionID`, `LogID`),
  INDEX `FK_LogSession_LogID_idx` (`LogID` ASC) VISIBLE,
  CONSTRAINT `FK_LogSession_ChargingSessionID`
    FOREIGN KEY (`ChargingSessionID`)
    REFERENCES `mydb`.`ChargingSessions` (`ChargingSessionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LogSession_LogID`
    FOREIGN KEY (`LogID`)
    REFERENCES `mydb`.`Logs` (`LogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sensors` (
  `SensorID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `SensorType` VARCHAR(45) NOT NULL,
  `Status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`SensorID`),
  INDEX `FK_Sensor_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_Sensor_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserDeploymentLocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserDeploymentLocation` (
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  `UserID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DeploymentLocationID`, `UserID`),
  INDEX `FK_UserDeploymentLocation_UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_UserDeploymentLocation_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_UserDeploymentLocation_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`Hosptial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hosptial` (
  `HosptialID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`HosptialID`),
  INDEX `FK_Hosptial_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Hosptial_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `WarehouseID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`WarehouseID`),
  INDEX `FK_Warehouse_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Warehouse_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Home` (
  `HomeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`HomeID`),
  INDEX `FK_Home_DeploymentLocation_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Home_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factory` (
  `FactoryID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`FactoryID`),
  INDEX `FK_Factory_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Factory_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `mydb`.`DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `DepartmentID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DepartmentName` VARCHAR(45) NOT NULL,
  `HosptialID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `FK_Department_HospitalID_idx` (`HosptialID` ASC) VISIBLE,
  CONSTRAINT `FK_Department_HospitalID`
    FOREIGN KEY (`HosptialID`)
    REFERENCES `mydb`.`Hosptial` (`HosptialID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AIModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AIModel` (
  `AIModelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ModelName` VARCHAR(45) NOT NULL,
  `ServiceType` VARCHAR(45) NOT NULL,
  `VersionLabel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AIModelID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmotionalPattern`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmotionalPattern` (
  `EmotionalPatternID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `AIModelID` INT UNSIGNED NOT NULL,
  `PatternSummary` TEXT NOT NULL,
  PRIMARY KEY (`EmotionalPatternID`),
  INDEX `FK_EmotionalPattern_RobotID_idx` (`RobotID` ASC) VISIBLE,
  INDEX `FK_EmotionalPattern_AIModelID_idx` (`AIModelID` ASC) VISIBLE,
  CONSTRAINT `FK_EmotionalPattern_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EmotionalPattern_AIModelID`
    FOREIGN KEY (`AIModelID`)
    REFERENCES `mydb`.`AIModel` (`AIModelID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MaintenanceRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MaintenanceRecord` (
  `MaintenanceRecordID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `TechinicianID` INT UNSIGNED NOT NULL,
  `RecordedAt` TIMESTAMP NOT NULL,
  `Description` TEXT NOT NULL,
  PRIMARY KEY (`MaintenanceRecordID`),
  INDEX `FK_MaintenanceRecord_RobotID_idx` (`RobotID` ASC) VISIBLE,
  INDEX `FK_MaintenanceRecord_TechinicianID_idx` (`TechinicianID` ASC) VISIBLE,
  CONSTRAINT `FK_MaintenanceRecord_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `mydb`.`Robots` (`RobotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MaintenanceRecord_TechinicianID`
    FOREIGN KEY (`TechinicianID`)
    REFERENCES `mydb`.`Technicians` (`TechnicianID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
