-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 17:41:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema robo_nexus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS robo_nexus;
USE robo_nexus;

DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `UserID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RobotRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RobotRoles` ;

CREATE TABLE IF NOT EXISTS `RobotRoles` (
  `RobotRoleID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotRole` ENUM("Senior", "Worker") NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `AIResponseID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotRoleID`),
  INDEX `FK_RobotRole_UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_RobotRole_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manufacturers` ;

CREATE TABLE IF NOT EXISTS `Manufacturers` (
  `ManufacturerID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ManufacturerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RobotModels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RobotModels` ;

CREATE TABLE IF NOT EXISTS `RobotModels` (
  `RobotModelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Model` ENUM("Model1", "Model2") NULL,
  `ManufacturerID` INT UNSIGNED NULL,
  PRIMARY KEY (`RobotModelID`),
  INDEX `FK_RobotModel_ManufacturerID_idx` (`ManufacturerID` ASC) VISIBLE,
  CONSTRAINT `FK_RobotModel_ManufacturerID`
    FOREIGN KEY (`ManufacturerID`)
    REFERENCES `Manufacturers` (`ManufacturerID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Addresses` ;

CREATE TABLE IF NOT EXISTS `Addresses` (
  `AddressID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(90) NOT NULL,
  `City` VARCHAR(90) NOT NULL,
  `State` CHAR(2) NOT NULL,
  `Zipcode` CHAR(5) NOT NULL,
  PRIMARY KEY (`AddressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeploymentLocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeploymentLocations` ;

CREATE TABLE IF NOT EXISTS `DeploymentLocations` (
  `DeploymentLocationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EnvironmentType` ENUM('HOME', 'HOSPITAL', 'WAREHOUSE', 'FACTORY') NOT NULL,
  `AddressID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DeploymentLocationID`),
  INDEX `FK_DeploymentLocation_AdressID_idx` (`AddressID` ASC) VISIBLE,
  CONSTRAINT `FK_DeploymentLocation_AdressID`
    FOREIGN KEY (`AddressID`)
    REFERENCES `Addresses` (`AddressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SoftwareVersions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SoftwareVersions` ;

CREATE TABLE IF NOT EXISTS `SoftwareVersions` (
  `SoftwareVersionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SoftwareVersionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Robots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Robots` ;

CREATE TABLE IF NOT EXISTS `Robots` (
  `RobotID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotRoleID` INT UNSIGNED NOT NULL,
  `RobotModelID` INT UNSIGNED NOT NULL,
  `DeploymentLocationID` INT UNSIGNED NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `SoftwareVersionID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotID`),
  INDEX `FK_Robot_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  INDEX `FK_Robot_RobotRoleID_idx` (`RobotRoleID` ASC) VISIBLE,
  INDEX `FK_Robot_RobotModelID_idx` (`RobotModelID` ASC) VISIBLE,
  INDEX `FK_Robot_SoftwareVersionID_idx` (`SoftwareVersionID` ASC) VISIBLE,
  INDEX `FK_Robot_UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FK_Robot_RobotRoleID`
    FOREIGN KEY (`RobotRoleID`)
    REFERENCES `RobotRoles` (`RobotRoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_RobotModelID`
    FOREIGN KEY (`RobotModelID`)
    REFERENCES `RobotModels` (`RobotModelID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Robot_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_SoftwareVersionID`
    FOREIGN KEY (`SoftwareVersionID`)
    REFERENCES `SoftwareVersions` (`SoftwareVersionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alerts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alerts` ;

CREATE TABLE IF NOT EXISTS `Alerts` (
  `AlertID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `Severity` ENUM('Low', 'Medium', 'High', 'Critical') NOT NULL,
  `TimeStamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`AlertID`),
  INDEX `FK_Alert_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_Alert_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PerformanceMetrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PerformanceMetrics` ;

CREATE TABLE IF NOT EXISTS `PerformanceMetrics` (
  `PerformanceMetricID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `MetricType` VARCHAR(45) NOT NULL,
  `MetricValue` INT UNSIGNED NOT NULL,
  `TimeStamp` DATETIME NOT NULL,
  PRIMARY KEY (`PerformanceMetricID`),
  INDEX `FK_PerformanceMetrics_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_PerformanceMetrics_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Technicians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Technicians` ;

CREATE TABLE IF NOT EXISTS `Technicians` (
  `TechnicianID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NULL,
  PRIMARY KEY (`TechnicianID`),
  INDEX `FK_Technician_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Technician_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks` ;

CREATE TABLE IF NOT EXISTS `Tasks` (
  `TaskID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TaskName` VARCHAR(64) NOT NULL,
  `Description` TEXT NOT NULL,
  `Priority` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `Status` TINYINT NOT NULL,
  PRIMARY KEY (`TaskID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskAssignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskAssignments` ;

CREATE TABLE IF NOT EXISTS `TaskAssignments` (
  `TaskAssignmentID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `TaskID` INT UNSIGNED NOT NULL,
  `AssignedAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`TaskAssignmentID`),
  INDEX `fk_TaskAssignments_Robots1_idx` (`RobotID` ASC) VISIBLE,
  INDEX `fk_TaskAssignments_Users1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_TaskAssignments_Tasks1_idx` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `FK_TaskAssignments_Robots1`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TaskAssignments_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TaskAssignments_Tasks1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `Tasks` (`TaskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskExecutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskExecutions` ;

CREATE TABLE IF NOT EXISTS `TaskExecutions` (
  `TaskExecutionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TaskID` INT UNSIGNED NOT NULL,
  `StartTime` TIMESTAMP NOT NULL,
  `EndTime` TIMESTAMP NOT NULL,
  `Status` TINYINT NOT NULL,
  PRIMARY KEY (`TaskExecutionID`),
  INDEX `fk_TaskExecutions_Tasks1_idx` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `FK_TaskExecutions_Tasks1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `Tasks` (`TaskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hardwares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hardwares` ;

CREATE TABLE IF NOT EXISTS `Hardwares` (
  `HardwareID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ManufacturerID` INT UNSIGNED NULL,
  PRIMARY KEY (`HardwareID`),
  INDEX `FK_Hardware_ManufacturerID_idx` (`ManufacturerID` ASC) VISIBLE,
  CONSTRAINT `FK_Hardwares_ManufacturerID`
    FOREIGN KEY (`ManufacturerID`)
    REFERENCES `Manufacturers` (`ManufacturerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RobotHardware`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RobotHardware` ;

CREATE TABLE IF NOT EXISTS `RobotHardware` (
  `RobotHardwareID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotHardwareID`),
  INDEX `FK_RobotHardware_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_RobotHardware_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChargingSessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChargingSessions` ;

CREATE TABLE IF NOT EXISTS `ChargingSessions` (
  `ChargingSessionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  `StartTime` TIMESTAMP NOT NULL,
  `EndTime` TIMESTAMP NULL,
  PRIMARY KEY (`ChargingSessionID`),
  INDEX `FK_ChargingSession_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_ChargingSession_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnergyStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnergyStatus` ;

CREATE TABLE IF NOT EXISTS `EnergyStatus` (
  `EnergyStatusID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ChargingSessionID` INT UNSIGNED NOT NULL,
  `BatteryLevel` TINYINT(3) UNSIGNED NOT NULL,
  `RecordedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `RobotID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EnergyStatusID`),
  INDEX `FK_EnergyStatus_ChargingSessionID_idx` (`ChargingSessionID` ASC) VISIBLE,
  INDEX `FK_EnergyStatus_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_EnergyStatus_ChargingSessionID`
    FOREIGN KEY (`ChargingSessionID`)
    REFERENCES `ChargingSessions` (`ChargingSessionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EnergyStatus_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChargingStations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChargingStations` ;

CREATE TABLE IF NOT EXISTS `ChargingStations` (
  `ChargingStationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `StationName` VARCHAR(64) NULL,
  `Capacity` TINYINT(3) UNSIGNED NOT NULL,
  `Status` ENUM('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'OFFLINE') NOT NULL DEFAULT 'AVAILABLE',
  PRIMARY KEY (`ChargingStationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ChargingStationSessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChargingStationSessions` ;

CREATE TABLE IF NOT EXISTS `ChargingStationSessions` (
  `ChargingSessionID` INT UNSIGNED NOT NULL,
  `ChargingStationID` INT UNSIGNED NOT NULL,
  `ChargingStationSessionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `FK_ChargingStationSession_ChargingSessionID_idx` (`ChargingSessionID` ASC) VISIBLE,
  INDEX `FK_ChargingStationSession_ChargingStationID_idx` (`ChargingStationID` ASC) VISIBLE,
  PRIMARY KEY (`ChargingStationSessionID`),
  CONSTRAINT `FK_ChargingStationSession_ChargingSessionID`
    FOREIGN KEY (`ChargingSessionID`)
    REFERENCES `ChargingSessions` (`ChargingSessionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ChargingStationSession_ChargingStationID`
    FOREIGN KEY (`ChargingStationID`)
    REFERENCES `ChargingStations` (`ChargingStationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RobotChargingStations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RobotChargingStations` ;

CREATE TABLE IF NOT EXISTS `RobotChargingStations` (
  `ChargingStationID` INT UNSIGNED NOT NULL,
  `RobotID` INT UNSIGNED NOT NULL,
  `RobotChargingStationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `FK_RobotChargingStation_RobotID_idx` (`RobotID` ASC) VISIBLE,
  PRIMARY KEY (`RobotChargingStationID`),
  CONSTRAINT `FK_RobotChargingStation_ChargingStationID`
    FOREIGN KEY (`ChargingStationID`)
    REFERENCES `ChargingStations` (`ChargingStationID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RobotChargingStation_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logs` ;

CREATE TABLE IF NOT EXISTS `Logs` (
  `LogID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EventType` VARCHAR(64) NOT NULL,
  `EventDetails` TEXT(150) NULL,
  PRIMARY KEY (`LogID`),
  INDEX `FK_Log_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_Log_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TechnicianNames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TechnicianNames` ;

CREATE TABLE IF NOT EXISTS `TechnicianNames` (
  `TechnicianNameID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TechnicianID` INT UNSIGNED NOT NULL,
  `FirstName` VARCHAR(64) NOT NULL,
  `LastName` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`TechnicianNameID`),
  INDEX `FK_TechnicanName_Technician_idx` (`TechnicianID` ASC) VISIBLE,
  CONSTRAINT `FK_TechnicanName_Technician`
    FOREIGN KEY (`TechnicianID`)
    REFERENCES `Technicians` (`TechnicianID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogSessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LogSessions` ;

CREATE TABLE IF NOT EXISTS `LogSessions` (
  `ChargingSessionID` INT UNSIGNED NOT NULL,
  `LogID` INT UNSIGNED NOT NULL,
  `LogSessionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `FK_LogSession_LogID_idx` (`LogID` ASC) VISIBLE,
  PRIMARY KEY (`LogSessionID`),
  CONSTRAINT `FK_LogSession_ChargingSessionID`
    FOREIGN KEY (`ChargingSessionID`)
    REFERENCES `ChargingSessions` (`ChargingSessionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LogSession_LogID`
    FOREIGN KEY (`LogID`)
    REFERENCES `Logs` (`LogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sensors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sensors` ;

CREATE TABLE IF NOT EXISTS `Sensors` (
  `SensorID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `SensorType` VARCHAR(45) NOT NULL,
  `Status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`SensorID`),
  INDEX `FK_Sensor_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_Sensor_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDeploymentLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserDeploymentLocation` ;

CREATE TABLE IF NOT EXISTS `UserDeploymentLocation` (
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `UserDeploymentLocationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INDEX `FK_UserDeploymentLocation_UserID_idx` (`UserID` ASC) VISIBLE,
  PRIMARY KEY (`UserDeploymentLocationID`),
  CONSTRAINT `FK_UserDeploymentLocation_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_UserDeploymentLocation_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `Hospitals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hospitals` ;

CREATE TABLE IF NOT EXISTS `Hospitals` (
  `HospitalID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`HospitalID`),
  INDEX `FK_Hosptial_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Hospitals_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Warehouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Warehouses` ;

CREATE TABLE IF NOT EXISTS `Warehouses` (
  `WarehouseID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`WarehouseID`),
  INDEX `FK_Warehouse_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Warehouses_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Homes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Homes` ;

CREATE TABLE IF NOT EXISTS `Homes` (
  `HomeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`HomeID`),
  INDEX `FK_Home_DeploymentLocation_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Homes_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Factories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Factories` ;

CREATE TABLE IF NOT EXISTS `Factories` (
  `FactoryID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DeploymentLocationID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`FactoryID`),
  INDEX `FK_Factory_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Factories_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `DepartmentID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DepartmentName` VARCHAR(45) NOT NULL,
  `HosptialID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `FK_Department_HospitalID_idx` (`HosptialID` ASC) VISIBLE,
  CONSTRAINT `FK_Department_HospitalID`
    FOREIGN KEY (`HosptialID`)
    REFERENCES `Hospitals` (`HospitalID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AIModels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AIModels` ;

CREATE TABLE IF NOT EXISTS `AIModels` (
  `AIModelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ModelName` VARCHAR(45) NOT NULL,
  `ServiceType` VARCHAR(45) NOT NULL,
  `VersionLabel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AIModelID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmotionalPatterns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmotionalPatterns` ;

CREATE TABLE IF NOT EXISTS `EmotionalPatterns` (
  `EmotionalPatternID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `AIModelID` INT UNSIGNED NOT NULL,
  `PatternSummary` TEXT NOT NULL,
  PRIMARY KEY (`EmotionalPatternID`),
  INDEX `FK_EmotionalPattern_RobotID_idx` (`RobotID` ASC) VISIBLE,
  INDEX `FK_EmotionalPattern_AIModelID_idx` (`AIModelID` ASC) VISIBLE,
  CONSTRAINT `FK_EmotionalPatterns_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EmotionalPatterns_AIModelID`
    FOREIGN KEY (`AIModelID`)
    REFERENCES `AIModels` (`AIModelID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MaintenanceRecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MaintenanceRecord` ;

CREATE TABLE IF NOT EXISTS `MaintenanceRecord` (
  `MaintenanceRecordID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `TechinicianID` INT UNSIGNED NOT NULL,
  `RecordedAt` TIMESTAMP NOT NULL,
  `Description` TEXT NOT NULL,
  PRIMARY KEY (`MaintenanceRecordID`),
  INDEX `FK_MaintenanceRecord_RobotID_idx` (`RobotID` ASC) VISIBLE,
  INDEX `FK_MaintenanceRecord_TechinicianID_idx` (`TechinicianID` ASC) VISIBLE,
  CONSTRAINT `FK_MaintenanceRecord_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MaintenanceRecord_TechinicianID`
    FOREIGN KEY (`TechinicianID`)
    REFERENCES `Technicians` (`TechnicianID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmotionalRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmotionalRecords` ;

CREATE TABLE IF NOT EXISTS `EmotionalRecords` (
  `Emotional_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EmotionalPatternID` INT UNSIGNED NOT NULL,
  `EmotionalState` ENUM("1", "2", "3") NOT NULL,
  `Timestamp` DATETIME NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Emotional_ID`),
  INDEX `FK_EmotionalRecord_EmotionalPatternID_idx` (`EmotionalPatternID` ASC) VISIBLE,
  CONSTRAINT `FK_EmotionalRecord_EmotionalPatternID`
    FOREIGN KEY (`EmotionalPatternID`)
    REFERENCES `EmotionalPatterns` (`EmotionalPatternID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InteractionSessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InteractionSessions` ;

CREATE TABLE IF NOT EXISTS `InteractionSessions` (
  `InteractionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `HomeID` INT UNSIGNED NOT NULL,
  `StartTIme` DATETIME NOT NULL,
  `EndTIme` DATETIME NOT NULL,
  PRIMARY KEY (`InteractionID`),
  INDEX `FK_InteractionSessions_RobotID_idx` (`RobotID` ASC) VISIBLE,
  INDEX `FK_InteractionSessions_UserID_idx` (`UserID` ASC) VISIBLE,
  INDEX `FK_InteractionSessions_HomeID_idx` (`HomeID` ASC) VISIBLE,
  CONSTRAINT `FK_InteractionSessions_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_InteractionSessions_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `Users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_InteractionSessions_HomeID`
    FOREIGN KEY (`HomeID`)
    REFERENCES `Homes` (`HomeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiagnosticReports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiagnosticReports` ;

CREATE TABLE IF NOT EXISTS `DiagnosticReports` (
  `DiagnosticReportID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `AIModelID` INT UNSIGNED NOT NULL,
  `GeneratedAt` DATETIME NOT NULL,
  `Summary` TEXT NOT NULL,
  PRIMARY KEY (`DiagnosticReportID`),
  INDEX `FK_DiagnosticReports_RobotId_idx` (`RobotID` ASC) VISIBLE,
  INDEX `FK_DiagnosticReports_AIModelID_idx` (`AIModelID` ASC) VISIBLE,
  CONSTRAINT `FK_DiagnosticReports_RobotId`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DiagnosticReports_AIModelID`
    FOREIGN KEY (`AIModelID`)
    REFERENCES `AIModels` (`AIModelID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SupportRequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SupportRequests` ;

CREATE TABLE IF NOT EXISTS `SupportRequests` (
  `SupportRequestID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `IssueDetails` TEXT NOT NULL,
  `TimeReported` DATETIME NOT NULL,
  PRIMARY KEY (`SupportRequestID`),
  INDEX `FK_SupportRequests_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_SupportRequests_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AIRequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AIRequests` ;

CREATE TABLE IF NOT EXISTS `AIRequests` (
  `AIRequestID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AIModelID` INT UNSIGNED NOT NULL,
  `RobotID` INT UNSIGNED NOT NULL,
  `RequestedAt` DATETIME NOT NULL,
  PRIMARY KEY (`AIRequestID`),
  INDEX `FK_AIRequests_RobotID_idx` (`RobotID` ASC) VISIBLE,
  INDEX `FK_AIRequests_AIModelID_idx` (`AIModelID` ASC) VISIBLE,
  CONSTRAINT `FK_AIRequests_AIModelID`
    FOREIGN KEY (`AIModelID`)
    REFERENCES `AIModels` (`AIModelID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_AIRequests_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AIResponses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AIResponses` ;

CREATE TABLE IF NOT EXISTS `AIResponses` (
  `AIResponseID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AIRequestsID` INT UNSIGNED NOT NULL,
  `RobotRoleID` INT UNSIGNED NOT NULL,
  `TaskID` INT UNSIGNED NOT NULL,
  `GeneratedAt` DATETIME NOT NULL,
  `Response` TEXT NOT NULL,
  PRIMARY KEY (`AIResponseID`),
  INDEX `FK_AIResponses_AIRequest_ID_idx` (`AIRequestsID` ASC) VISIBLE,
  INDEX `FK_AIResponses_TaskID_idx` (`TaskID` ASC) VISIBLE,
  INDEX `FK_AIResponses_RobotRoleID_idx` (`RobotRoleID` ASC) VISIBLE,
  CONSTRAINT `FK_AIResponses_AIRequestID`
    FOREIGN KEY (`AIRequestsID`)
    REFERENCES `AIRequests` (`AIRequestID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_AIResponses_TaskID`
    FOREIGN KEY (`TaskID`)
    REFERENCES `Tasks` (`TaskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_AIResponses_RobotRoleID`
    FOREIGN KEY (`RobotRoleID`)
    REFERENCES `RobotRoles` (`RobotRoleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmotionalAnalyzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmotionalAnalyzes` ;

CREATE TABLE IF NOT EXISTS `EmotionalAnalyzes` (
  `EmotionalAnalyzeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EmotionalID` INT UNSIGNED NOT NULL,
  `AIRequestID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EmotionalAnalyzeID`),
  INDEX `FK_EmotionalAnalyzes_EmotionalID_idx` (`EmotionalID` ASC) VISIBLE,
  INDEX `FK_EmotionalAnalyzes_AIRequestID_idx` (`AIRequestID` ASC) VISIBLE,
  CONSTRAINT `FK_EmotionalAnalyzes_EmotionalID`
    FOREIGN KEY (`EmotionalID`)
    REFERENCES `EmotionalRecords` (`Emotional_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EmotionalAnalyzes_AIRequestID`
    FOREIGN KEY (`AIRequestID`)
    REFERENCES `AIRequests` (`AIRequestID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PerformanceDiagnostics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PerformanceDiagnostics` ;

CREATE TABLE IF NOT EXISTS `PerformanceDiagnostics` (
  `PerformanceDiagnosticID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DiagnosticReportID` INT UNSIGNED NOT NULL,
  `PerformanceMetricID` INT UNSIGNED NOT NULL,
  `PerformanceDiagnosticscol` VARCHAR(45) NULL,
  PRIMARY KEY (`PerformanceDiagnosticID`),
  INDEX `FK_PerformanceDiagnostics_DiagnosticReportID_idx` (`DiagnosticReportID` ASC) VISIBLE,
  INDEX `FK_PerformanceDiagnostics_PerformanceMetricID_idx` (`PerformanceMetricID` ASC) VISIBLE,
  CONSTRAINT `FK_PerformanceDiagnostics_DiagnosticReportID`
    FOREIGN KEY (`DiagnosticReportID`)
    REFERENCES `DiagnosticReports` (`DiagnosticReportID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PerformanceDiagnostics_PerformanceMetricID`
    FOREIGN KEY (`PerformanceMetricID`)
    REFERENCES `PerformanceMetrics` (`PerformanceMetricID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmotionalInteractionSessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmotionalInteractionSessions` ;

CREATE TABLE IF NOT EXISTS `EmotionalInteractionSessions` (
  `EmotionalInteractionSessionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EmotionalID` INT UNSIGNED NOT NULL,
  `InteractionID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EmotionalInteractionSessionID`),
  INDEX `FK_EmotionalInteractionSessions_EmotionalID_idx` (`EmotionalID` ASC) VISIBLE,
  INDEX `FK_EmotionalInteractionSessions_InteractionID_idx` (`InteractionID` ASC) VISIBLE,
  CONSTRAINT `FK_EmotionalInteractionSessions_EmotionalID`
    FOREIGN KEY (`EmotionalID`)
    REFERENCES `EmotionalRecords` (`Emotional_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EmotionalInteractionSessions_InteractionID`
    FOREIGN KEY (`InteractionID`)
    REFERENCES `InteractionSessions` (`InteractionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TechnicianSupportRequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TechnicianSupportRequests` ;

CREATE TABLE IF NOT EXISTS `TechnicianSupportRequests` (
  `TechnicianSupportRequestID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SupportRequestID` INT UNSIGNED NOT NULL,
  `TechnicianID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`TechnicianSupportRequestID`),
  INDEX `FK_TechnicianSupportRequests_SupportRequest_idx` (`SupportRequestID` ASC) VISIBLE,
  INDEX `FK_TechnicianSupportRequests_TechnicianID_idx` (`TechnicianID` ASC) VISIBLE,
  CONSTRAINT `FK_TechnicianSupportRequests_SupportRequestID`
    FOREIGN KEY (`SupportRequestID`)
    REFERENCES `SupportRequests` (`SupportRequestID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TechnicianSupportRequests_TechnicianID`
    FOREIGN KEY (`TechnicianID`)
    REFERENCES `Technicians` (`TechnicianID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HardwareMaintenances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HardwareMaintenances` ;

CREATE TABLE IF NOT EXISTS `HardwareMaintenances` (
  `HardwareMaintenancesID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `HardwareID` INT UNSIGNED NOT NULL,
  `MaintenanceRecordID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`HardwareMaintenancesID`),
  INDEX `FK_HardwareMaintenances_HardwareID_idx` (`HardwareID` ASC) VISIBLE,
  INDEX `FK_HardwareMaintenances_MaintenanceRecordID_idx` (`MaintenanceRecordID` ASC) VISIBLE,
  CONSTRAINT `FK_HardwareMaintenances_HardwareID`
    FOREIGN KEY (`HardwareID`)
    REFERENCES `Hardwares` (`HardwareID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_HardwareMaintenances_MaintenanceRecordID`
    FOREIGN KEY (`MaintenanceRecordID`)
    REFERENCES `MaintenanceRecord` (`MaintenanceRecordID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PatientEmotionalRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PatientEmotionalRecords` ;

CREATE TABLE IF NOT EXISTS `PatientEmotionalRecords` (
  `PatientEmotionalRecordID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EmotionalID` INT UNSIGNED NOT NULL,
  `HospitalID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`PatientEmotionalRecordID`),
  INDEX `FK_PatientEmotionalRecords_EmotionalID_idx` (`EmotionalID` ASC) VISIBLE,
  INDEX `FK_PatientEmotionalRecords_HospitalID_idx` (`HospitalID` ASC) VISIBLE,
  CONSTRAINT `FK_PatientEmotionalRecords_EmotionalID`
    FOREIGN KEY (`EmotionalID`)
    REFERENCES `EmotionalRecords` (`Emotional_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PatientEmotionalRecords_HospitalID`
    FOREIGN KEY (`HospitalID`)
    REFERENCES `Hospitals` (`HospitalID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
