# base.py
#
# This file defines the `Base` class, which serves as the foundation for all ORM models.
# The `Base` class provides essential methods for interacting with the database, such as:
#   - `save()`: Insert or update the current model instance in the database.
#   - `_insert()`: Insert the current instance into the database (private method).
#   - `_update()`: Update the current instance in the database (private method).
#   - `get()`: Retrieve a record by its ID.
#   - `delete()`: Delete a record by its ID.
#   - `all()`: Retrieve all records of the model from the database.
#   - `query()`: Query records based on filter conditions.
#   - `create_schema()`: Generate the schema (sql code) for the model in the database.
#   - `create()`: Uses the generated schema from the previous function to create a table in the database based on the model's schema.
#   - `join()`: Join multiple models together for data retrieval.
#   - `where()`: Add WHERE conditions to queries.
#   - `having()`: Add HAVING conditions to queries.
#   - `group_by()`: Add GROUP BY clauses to queries.
#
# Connection management is critical. Every method interacting with the database must:
#   - Open a new connection and cursor at the start of the operation.
#   - Close the cursor and connection after the operation is complete,
#     whether the operation is successful or not, to avoid memory leaks.
#   - Transactions must be committed on success, and rolled back on failure.
#
# Students should implement proper connection management in each method, including:
#   - Using `try`, `except`, and `finally` to ensure the connection and cursor are always closed.
#   - Handling potential exceptions during database operations and performing rollbacks if needed.
#
# The `Base` class is meant to be subclassed, and any model that extends `Base` will automatically
# inherit the methods for database interaction.


from api.db_connectors import MySQL
from api.columns import Column



class Base:
    """
    example of registry
    track7 = Track.get(id=7)
    """
    _registry = {} # {key='Track', value=Track}
    _identity_map = {} # {key='Track', value=7}

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        Base._registry[cls.table_descriptor()] = cls



    def __init__(self, **kwargs):
        """Initialize model instance with attributes."""
        for key, value in kwargs.items():
            setattr(self, key, value)


    def save(self):
        """Insert or update the record in the database.
        """
        pk = self.primary_key()

        if pk in self.__dict__ and self.__dict__[pk] is not None:
            print("I am updating...")
            self._update()
        else:
            print("I am inserting")
            self._insert()


    def _insert(self):
        """Insert the current instance into the database.
        """
        # INSERT INTO <table> (attributes separated by comma) VALUES
        #                      (placeholders separated by comma)
        table = self.table_descriptor()
        columns = self.columns()
        attributes = [attr for attr, column in columns.items() if not column.is_primary_key()]
        fields = ", ".join(attributes)
        values = [self.__dict__[attr] for attr in attributes]
        placeholders = ", ".join(["%s"] * len(attributes))

        # INSERT INTO Artist (name) VALUES (%s)
        # INSERT INTO Album (title, year_released) VALUES (%s, %s)
        query = f"INSERT INTO {table} ({fields}) VALUES ({placeholders})"

        connection, cursor = MySQL.instance()

        try:
            cursor.execute(query, values)
            connection.commit()
            pk_value = cursor.lastrowid
            if pk_value:
                pk = self.primary_key() # artist_id
                setattr(self, pk, pk_value) # new id generated by the insert and assigning it to that pk


        except Exception as e :
            # handle errors and any rollbacks
            connection.rollback()
            raise e

        finally:
            # close components to avoid memory leaks
            connection.close()
            cursor.close()






    def _update(self):
        """Update the current instance in the database.
        """
        # UPDATE <table> SET <attr1=placehoder1>, <attr2=placeholder2>, ...
        #                    <attrn=placeholdern> WHERE <pk> = <placehoder>

        table = self.table_descriptor()
        columns = self.columns()
        attributes = [attr for attr, column in columns.items() if not column.is_primary_key()]
        values = [self.__dict__[attr] for attr in attributes]
        pk = self.primary_key()
        pk_value = getattr(self, pk, None)
        values.append(pk_value)
        fields = [f"{attr}=%s" for attr in attributes]
        fields_separated_by_comma = ", ".join(fields)

        query = f"UPDATE {table} SET {fields_separated_by_comma} WHERE {pk} = %s"
        print(query)
        connection, cursor = MySQL.instance()

        try:
            cursor.execute(query, values)
            connection.commit()
        except Exception as e:
            # handle errors and any rollbacks
            connection.rollback()
            raise e

        finally:
            # close components to avoid memory leaks
            connection.close()
            cursor.close()

    @classmethod
    def get(cls, id):
        key = cls.identity_key(id)

        if key in cls._identity_map:
            return cls.get_identity_instance(id)

        table = cls.table_descriptor()
        pk = cls.primary_key()
        query = f"SELECT * FROM {table} WHERE {pk} = %s"

        connection, cursor = MySQL.instance()

        try:
            cursor.execute(query, (id,))
            result = cursor.fetchone()

            if result is None:
                return None

            obj = cls(**result)
            cls.add_identity_instance(obj)
            return obj

        except Exception as e:
            raise e

        finally:
            connection.close()
            cursor.close()

    @classmethod
    def delete(cls, id):
        """Delete a record from the database by its ID.

        TODO:
            - Open a connection and cursor.
            - Construct the `DELETE` SQL query to remove the record by its primary key (`id`).
            - Ensure the connection and cursor are properly closed after the operation.
            - Commit the transaction if successful; rollback if there's an error.
        """
        pass

    @classmethod
    def all(cls):
        """Retrieve all records of this model from the database.
        """
        # SELECT * FROM <table>
        table = cls.table_descriptor()

        query = f"SELECT * FROM {table}"

        connection, cursor = MySQL.instance()

        try:
            cursor.execute(query)
            results = cursor.fetchall()
            all_results = []
            for result in results:
                all_results.append(cls(**result))
            return all_results

        except Exception as e:
            # handle errors and any rollbacks
            raise e

        finally:
            # close components to avoid memory leaks
            connection.close()
            cursor.close()



    @classmethod
    def query(cls, **filters):
        """Query records based on filters.

        TODO:
            - Open a connection and cursor.
            - Construct the `SELECT` SQL query using the provided filters as conditions.
            - Ensure the connection and cursor are properly closed after the operation.
            - Return the results as instances of the model.
        """
        pass

    @classmethod
    def create(cls, **attributes):
        """Insert a new record in an existing schema without exposing the class constructor.
        """
        object = cls(**attributes)
        object._insert()
        return object

    @classmethod
    def create_schema(cls):
        """Generate the schema for the model in the database.

        TODO:
            - Open a connection and cursor.
            - Construct the `CREATE SCHEMA` SQL query using the provided descriptor.
            - Ensure the connection and cursor are properly closed after the operation.
            - Commit the transaction if successful; rollback if there's an error.
        """
        pass

    @classmethod
    def join(cls, models):
        """Join multiple models to organize your data.

        TODO:
            - Open a connection and cursor.
            - Construct the appropriate `JOIN` SQL query to combine data from multiple models.
            - Ensure the connection and cursor are properly closed after the operation.
            - Return the joined results.
        """
        pass

    @classmethod
    def where(cls, **conditions):
        """Add WHERE conditions to a query.

        TODO:
            - This method should help in adding WHERE conditions to any SELECT query.
            - Build the WHERE clause dynamically based on the given conditions (e.g., `WHERE column = value`).
            - Return the generated WHERE condition string.
        """
        pass

    @classmethod
    def having(cls, **conditions):
        """Add HAVING conditions to a query.

        TODO:
            - This method should help in adding HAVING conditions to a query.
            - Construct the HAVING clause dynamically (useful when performing aggregate functions).
            - Return the generated HAVING condition string.
        """
        pass

    @classmethod
    def group_by(cls, *columns):
        """Add GROUP BY clauses to a query.

        TODO:
            - This method should help in adding GROUP BY clauses to any SELECT query.
            - Construct the GROUP BY clause dynamically based on the provided columns (e.g., `GROUP BY column1, column2`).
            - Return the generated GROUP BY condition string.
        """
        pass

    @classmethod
    def table_descriptor(cls):
        """
        :return: the name of the table t
        """
        return cls.__name__


    @classmethod
    def columns(cls):
        """
        :return: the list of column names
        """
        return {name:column for name, column in cls.__dict__.items() if isinstance(column, Column)}



    @classmethod
    def primary_key(cls):
        """
        :return: the primary key attribute name, not the value.
                 for example student_id = 1, will return student_id, not the value 1
        """
        columns = cls.columns()
        for name, column in columns.items():
            if column.is_primary_key():
                return name
        return 'id'

    @classmethod
    def resolve_model(cls, model_name):
        return cls._registry[model_name] # return Track class

    @classmethod
    def identity_key(cls, pk_value):

        return (cls.table_descriptor(), pk_value)

    @classmethod
    def get_identity_instance(cls, pk_value):

        key = cls.identity_key(pk_value)

        return cls._identity_map.get(key)

    @classmethod
    def add_identity_instance(cls, obj):

        pk = cls.primary_key()

        pk_value = getattr(obj, pk, None)

        if pk_value is None:
            return obj

        key = cls.identity_key(pk_value)

        cls._identity_map[key] = obj

        return obj

